[package]
name = 'alvr_server'
version = '13.0.0-alpha.1'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[lib]
crate-type = ['cdylib']

[dependencies]
alvr_common = { path = '../common' }
settings-schema = { git = 'https://github.com/zarik5/settings-schema-rs', features = ['rename_camel_case'] }
parking_lot = '^0.11.0'
nalgebra = '^0.22.0'
chrono = '^0.4.13'
log = '^0.4.8'
fern = '^0.6.0'
serde_json = '^1.0.53'
lazy_static = '^1.4.0'
lazy-static-include = '^3.0'
futures = '^0.3.5'
tokio = { version = '^0.2.22', features = ['rt-threaded'] }
warp = '=0.2.3'

[build-dependencies]
walkdir = '^2.3'
cc = { version = '^1.0', features = ["parallel"] }
bindgen = '^0.55.0'
