[package]
name = 'alvr_launcher'
version = '13.0.0-alpha.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
single-instance = '^0.1.2'
log = '^0.4.8'
fern = '^0.6.0'
msgbox = { git = 'https://github.com/bekker/msgbox-rs' } 
alcro = '^0.1.4'
alvr_common = { path = '../common' }

[target.'cfg(windows)'.build-dependencies]
winres = '^0.1.11'
