[package]
name = 'alvr_launcher'
version = '13.0.0-alpha.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
alvr_common = { path = '../common' }
single-instance = '^0.1.2'
alcro = '^0.2.0'
serde_json = '^1.0.57'

[target.'cfg(windows)'.build-dependencies]
winres = '^0.1.11'
