[package]
name = 'alvr_client'
version = '13.0.0-alpha.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
alvr_common = { path = '../common' }
