[package]
name = 'alvr_client'
version = '13.0.0-alpha.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[lib]
crate_type = ["staticlib", "dylib"]

[dependencies]
alvr_common = { path = '../common' }
ndk = '0.1.0'

# [build-dependencies]
# walkdir = '^2.3'
# cc = { version = '^1.0', features = ["parallel"] }
# bindgen = '^0.55.0'