[package]
name = 'alvr_client'
version = '13.0.0-alpha.1'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[lib]
crate_type = ["staticlib", "cdylib"]

[dependencies]
parking_lot = '^0.11.0'
lazy_static = '^1.4'
log = '^0.4.8'
nalgebra = '^0.22.0'
serde_json = '1.0'
settings-schema = { git = 'https://github.com/zarik5/settings-schema-rs' }
alvr_common = { path = '../common' }
futures = '^0.3.5'
tokio = { version = '^0.2.22', features = ['rt-threaded'] }

# todo: move to target_os = "android"
jni = '^0.17.0'

[target.'cfg(target_os = "android")'.dependencies]
android_logger = '^0.9.0'

[build-dependencies]
walkdir = '^2.3'
cc = { version = '^1.0', features = ["parallel"] }
bindgen = '^0.55.0'
