[package]
name = 'alvr_common'
version = '13.0.0-alpha.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
rand = '^0.7.3'
parking_lot = '^0.11.0'
bitflags = '^1.2'
regex = '^1.3.9'
semver = '^0.10.0'
log = '^0.4.8'
backtrace = '^0.3.46'
settings-schema = { git = 'https://github.com/zarik5/settings-schema-rs', features = ['rename_camel_case'] }
sysinfo = '^0.15.0'
runas = '^0.2.1'
nalgebra = { version = '^0.21.1', features = ["serde-serialize"] }
serde = { version = '^1.0', features = ['derive'] }
serde_json = '^1.0'
bincode = '^1.3.1'
async-bincode = '^0.5.1'
futures = '^0.3.5'
tokio = { version = '^0.2.20', features = ['macros', 'process', 'io-util', 'stream', 'udp', 'tcp', 'time'] }
rcgen = '^0.8.5'
quinn = { git = 'https://github.com/djc/quinn' } # todo: use registry version (>0.6.1)
# cpal = { git = 'https://github.com/RustAudio/cpal' }

[target.'cfg(windows)'.dependencies]
winapi = { version = '^0.3.8', features = [
    'mmdeviceapi',
    'propsys',
    'coml2api',
    'propidl',
    'functiondiscoverykeys_devpkey',
    'wtypes',
    'objbase',
] }
wio = '^0.2.2'
widestring = '^0.4.2'
winreg = '^0.7.0'

[target.'cfg(not(windows))'.dependencies]
dirs = '^3.0.1'

[target.'cfg(not(android))'.dependencies]
msgbox = { git = 'https://github.com/bekker/msgbox-rs' }

[build-dependencies]
toml = '^0.5.6'
