[package]
name = 'alvr_common'
version = '1.0.0'
authors = ['Riccardo Zaglia <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
settings-schema = { git = 'https://github.com/zarik5/settings-schema-rs', features = ['rename_camel_case'] }
rand = '^0.7.3'
lazy_static = '^1.4.0'
parking_lot = '^0.11.0'
bitflags = '^1.2'
semver = { version = '^0.10.0', features = ['serde'] }
log = '^0.4.8'
backtrace = '^0.3.46'
nalgebra = { version = '^0.22.0', features = ["serde-serialize"] }
serde = { version = '^1.0', features = ['derive'] }
serde_json = '^1.0'
bincode = '^1.3'
serde_bytes = '^0.11.5'
futures = '^0.3.5'
tokio = { version = '^0.2.20', features = ['macros', 'net', 'sync'] }
tokio-util = { version = '^0.3.1', features = ['codec', 'udp'] }
bytes = '^0.5.6'
rcgen = '^0.8.5'
quinn = { git = 'https://github.com/djc/quinn', branch = 'main' }# todo: use registry version (>0.6.1)
gfx-hal = '^0.6.0'
# cpal = '^0.12.1'

[target.'cfg(not(target_os = "android"))'.dependencies]
dirs = '^3.0.1'
sysinfo = '^0.15.0'
runas = '^0.2.1'
msgbox = { git = 'https://github.com/bekker/msgbox-rs' }

[target.'cfg(windows)'.dependencies]
winapi = { version = '^0.3.8', features = [
    'impl-default',
    'mmdeviceapi',
    'propsys',
    'coml2api',
    'propidl',
    'functiondiscoverykeys_devpkey',
    'wtypes',
    'objbase',
] }
wio = '^0.2.2'
widestring = '^0.4.2'
gfx-backend-dx11 = '^0.6.0'

[build-dependencies]
alvr_xtask = { path = '../xtask' }
